### ISSUE TITLE
Error in launching local host

### ISSUE THREAD

**Issue by apal6** [LaughneyLab/ContactTracing_tutorial#1]
Hi,

Thank you for the package! 
I am trying to launch jupyter using ` This should provide the URL/token (generated using `docker run --rm -d -v $WORKDIR:/data -p 8888:8888 docker.io/biohpc/scrna2023 /root/scripts/startJupyter.sh /data)` you need to log into the jupyter notebook` but it says the token is invalid. I tried different ports but doesn't fix. 

<img width="723" alt="Screenshot 2023-08-28 at 9 04 45 AM" src="https://github.com/LaughneyLab/ContactTracing_tutorial/assets/127814354/d203d7b9-1786-460c-bf13-1d479c3e6816">

Any tips on how to solve this? 

Thank you

**Comment by Ziyan-Lin** [comment]
Hi, I have the same issue. May I ask how did you solve it? 
Many thanks!

**Comment by apal6** [comment]
Hi @Ziyan-Lin, 

I was not able to launch the jupyter notebook. I tried singularity too but no luck. Instead started working with another package for cell-cell communication by someone at Stanford (https://github.com/BlishLab/scriabin) and seems to work. 

Would be happy to know it it worked for anyone here or is there anything that I am doing wrong. 

Best regards,
Aastha
